import React, { useState } from 'react';
import {
  AppBar,
  Avatar,
  BottomNavigation,
  BottomNavigationAction,
  Box,
  CssBaseline,
  FormControl,
  IconButton,
  InputBase,
  List,
  ListItem,
  ListItemAvatar,
  ListItemText,
  Paper,
  TextField,
  Toolbar,
  Typography,
} from '@mui/material'
import Message from './Message';
import { BottomNav, Chat, TextF } from './ChatWindow.module';
import RestoreIcon from '@mui/icons-material/Restore';
import FavoriteIcon from '@mui/icons-material/Favorite';
import LocationOnIcon from '@mui/icons-material/LocationOn';
import './Chat.css'
import AddReactionIcon from '@mui/icons-material/AddReaction';


function refreshMessages() {
  const getRandomInt = (max) => Math.floor(Math.random() * Math.floor(max));

  return Array.from(new Array(50)).map(
    () => messageExamples[getRandomInt(messageExamples.length)],
  );
}

function ownOrAuthor() {
  // Generate a random number between 0 and 1
  const randomNumber = Math.random();

  // If the random number is less than 0.5, return 'own'
  if (randomNumber < 0.5) {
    return 'my';
  } 
  // Otherwise, return 'author'
  else {
    return 'other';
  }
}


function ChatWindow() {
  const [value, setValue] = React.useState(0);
  const ref = React.useRef(null);
  const [messages, setMessages] = React.useState(() => refreshMessages());

  React.useEffect(() => {
    ref.current.ownerDocument.body.scrollTop = 0;
    setMessages(refreshMessages());
  }, [value, setMessages]);

  return (
    <Box  sx={{ pb: 7, background:'#141416' }} ref={ref}>
      <CssBaseline />
      <List>
        {messages.map(({ primary, secondary, person }, index) => (
          <ListItem  button key={index + person}>
           <Message type={ownOrAuthor()}/>
          </ListItem>
        ))}
      </List>
      <Paper sx={{ position: 'fixed', pb:2,pt:2, bottom: 0, left: 0, right: 0, backgroundColor:'#1C1D22' }} elevation={3}>
        <BottomNavigation
          showLabels
          sx={{backgroundColor:'#1C1D22'}}
          value={value}
          onChange={(event, newValue) => {
            setValue(newValue);
          }}
        >
              <Box
      component="form"
      sx={{
        '& .MuiTextField-root': { m: 1, width: '50ch' },
      }}
      noValidate
      autoComplete="off"
    >
      <AddReactionIcon sx={{color:'#F1F0F0', marginTop:'12px'}}/>
        <TextF
          id="outlined-multiline-flexible"
          label="Write a message"
          size="small"
          multiline
          className='textfield'
          maxRows={4}
          InputLabelProps={{className: 'textfield__label'}}
          sx={{ '& label.Mui-focused': {
            color: 'rgba(255,255,255,0.6)'
          },
          '& .MuiInput-underline:after': {
            borderBottomColor: 'rgba(255,255,255,0.6)',
          },
          '& .MuiOutlinedInput-root': {
            '& fieldset': {
              borderColor: 'rgba(255,255,255,0.6)',
            },
            '&:hover fieldset': {
              borderColor: 'rgba(255,255,255,0.6)',
            },
            '&:hover ': {
              borderColor: 'rgba(255,255,255,0.6)',
            },
            '&.Mui-focused fieldset': {
              borderColor: 'whirgba(255,255,255,0.6)te',
            }}}}
        />
    </Box>
          <BottomNavigationAction label="Favorites"  style={{ color: 'rgba(255,255,255,0.6)' }} icon={<FavoriteIcon style={{ color: 'rgba(255,255,255,0.6)' }} />} />
        </BottomNavigation>
      </Paper>
    </Box>
  );
}

const messageExamples = [
  {
    primary: 'Brunch this week?',
    secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: '/static/images/avatar/5.jpg',
  },
  {
    primary: 'Birthday Gift',
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: '/static/images/avatar/1.jpg',
  },
  {
    primary: 'Recipe to try',
    secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
    person: '/static/images/avatar/2.jpg',
  },
  {
    primary: 'Yes!',
    secondary: 'I have the tickets to the ReactConf for this year.',
    person: '/static/images/avatar/3.jpg',
  },
  {
    primary: "Doctor's Appointment",
    secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
    person: '/static/images/avatar/4.jpg',
  },
  {
    primary: 'Discussion',
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: '/static/images/avatar/5.jpg',
  },
  {
    primary: 'Summer BBQ',
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: '/static/images/avatar/1.jpg',
  },
];





export default ChatWindow;